title: Researcher
url: "https://yuviabhi.github.io"
baseurl: "/clean"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/clean/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
